name: IceBlade
version: ${project.version}
main: me.burzakrual.iceblade.Main
api-version: 1.16
authors: [ BurzaKrual, Snozzlebot ]
description: Custom İtems
commands:
  iceblade:
    description: Iceblade
    usage: /<command>